
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_ACC_ADAPTOR)	+= sensor-scp-acc-adaptor.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_ACC_ADAPTOR)	+= sensor-scp-acc-gyr-i2c-drv.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_ACC_ADAPTOR)	+= sensor-scp-acc.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_ACC_ADAPTOR)	+= sensor-scp-gyr-adaptor.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_ACC_ADAPTOR)	+= sensor-scp-gyr.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_MAG_ADAPTOR)	+= sensor-scp-mag-adaptor.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_MAG_ADAPTOR)	+= sensor-scp-mag-i2c-drv.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_MAG_ADAPTOR)	+= sensor-scp-mag.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_PRES_ADAPTOR)	+= sensor-scp-pres-adaptor.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_PRES_ADAPTOR)	+= sensor-scp-pres-i2c-drv.o
obj-$(CONFIG_MEIZU_SENSOR_MTK_SCP_PRES_ADAPTOR)	+= sensor-scp-pres.o