subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
subdir-ccflags-y += -I$(srctree)/drivers/spi/mediatek/mt6797/
#obj-$(CONFIG_FINGERPRINT_FPC) += fpc_ree/
#obj-$(CONFIG_FINGERPRINT_GOODIX) += goodix_tee/
#obj-$(CONFIG_FINGERPRINT_GOODIX) += goodix_ree/
obj-y += fpc_ree/
obj-y += goodix_tee/
obj-y += goodix_ree/
