ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensorHub/inc_v1

obj-$(CONFIG_MEIZU_SENSOR_MAG_MTK_AKM0991X)	+= sensor-mag-dev-akm0991x.o
