
#ifndef SPI_PIN_CONFIG_H
#define SPI_PIN_CONFIG_H

#define CUST_EINT_FP_NUM		9 // EINT9
#define CUST_EINT_FP_DEBOUNCE_CN	0
#define CUST_EINT_FP_TYPE		CUST_EINTF_TRIGGER_RISING
#define CUST_EINT_FP_DEBOUNCE_EN	CUST_EINT_DEBOUNCE_DISABLE

#define GPIO_FP_INT_PIN         (GPIO86 | 0x80000000)
#define GPIO_FP_INT_PIN_M_EINT  GPIO_MODE_00
#define GPIO_FP_INT_PIN_M_GPIO  GPIO_MODE_00

#define GPIO_FP_RESET_PIN         (GPIO253 | 0x80000000)
#define GPIO_FP_RESET_PIN_M_GPIO  GPIO_MODE_00

#define GPIO_FP_SPICS_PIN         (GPIO237 | 0x80000000)
#define GPIO_FP_SPICS_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_FP_SPICS_PIN_M_SPI_CSA   GPIO_MODE_01

#define GPIO_FP_SPICLK_PIN         (GPIO234 | 0x80000000)
#define GPIO_FP_SPICLK_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_FP_SPICLK_PIN_M_SPI_CKA   GPIO_MODE_01

#define GPIO_FP_SPIMISO_PIN         (GPIO235 | 0x80000000)
#define GPIO_FP_SPIMISO_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_FP_SPIMISO_PIN_M_SPI_MIA   GPIO_MODE_01

#define GPIO_FP_SPIMOSI_PIN         (GPIO236 | 0x80000000)
#define GPIO_FP_SPIMOSI_PIN_M_GPIO  GPIO_MODE_00
#define GPIO_FP_SPIMOSI_PIN_M_SPI_MOA   GPIO_MODE_01

#endif