
obj-$(CONFIG_MEIZU_SENSOR_PS_ADAPTOR)	+= sensor-ps-adaptor.o
obj-$(CONFIG_MEIZU_SENSOR_PS_ADAPTOR)	+= sensor-ps-i2c-drv.o
obj-$(CONFIG_MEIZU_SENSOR_PS_ADAPTOR)	+= sensor-ps-statistics.o
obj-$(CONFIG_MEIZU_SENSOR_PS_ADAPTOR)	+= sensor-ps.o
