
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/core
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/utils

#obj-y	+= accelerometer/
obj-$(CONFIG_MEIZU_SENSOR_ALS_ADAPTOR)		+= light/
obj-$(CONFIG_MEIZU_SENSOR_PRES_ADAPTOR)		+= pressure/
obj-$(CONFIG_MEIZU_SENSOR_PS_ADAPTOR)		+= proximity/
obj-y	+= sensorhub/
obj-y	+= temperature/
