ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensorHub/inc_v1
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)

obj-$(CONFIG_MEIZU_SENSOR_ACC_GYR_MTK_LSM6DS3)	+= sensor-acc-gyr-dev-lsm6ds3.o
