#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#
ccflags-y += -I$(srctree)drivers/misc/mediatek/mach/mt6795/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/Mz_ft8716
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/Mz_ft8716/focaltech_test
	
obj-y += focaltech_test.o
obj-y += focaltech_test_main.o
obj-y += focaltech_test_ini.o
obj-y += focaltech_test_global.o
obj-y += focaltech_ic_table.o
obj-y += focaltech_test_detail_threshold.o	
obj-y += focaltech_test_config_ft8716.o
obj-y += focaltech_test_ft8716.o



