
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/core
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/utils
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/accelerometer
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/light
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/pressure
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/proximity
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/temperature
subdir-ccflags-y += -I$(srctree)/drivers/misc/meizu/sensor/adaptor/sensorhub/mtk

obj-$(CONFIG_MEIZU_SENSOR)	+= core/
obj-$(CONFIG_MEIZU_SENSOR)	+= utils/
obj-$(CONFIG_MEIZU_SENSOR)	+= adaptor/
obj-$(CONFIG_MEIZU_SENSOR)	+= chips/