obj-$(CONFIG_SND_SOC_TFA98XX) += tfa98xx.o tfa_dsp.o tfa_container.o

obj-$(CONFIG_SND_SOC_TFA98XX) += tfa9887_init.o tfa9887B_init.o tfa9888_init.o tfa9890_init.o tfa9891_init.o tfa9897_init.o

obj-$(CONFIG_SND_SOC_TFA98XX) += tfa_i2c.o tfa_tapdet.o